/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as BuyTokenRouteImport } from './routes/buy.$token'
import { Route as InvoiceOrderNumberRouteImport } from './routes/invoice.$orderNumber'
import { Route as OrderOrderNumberRouteImport } from './routes/order.$orderNumber'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin.admins'
import { Route as AuthenticatedAdminAgentsRouteImport } from './routes/_authenticated/admin.agents'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin.pages'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminSalesRouteImport } from './routes/_authenticated/admin.sales'
import { Route as AuthenticatedAgentIndexRouteImport } from './routes/_authenticated/agent.index'
import { Route as AuthenticatedAgentCustomersRouteImport } from './routes/_authenticated/agent.customers'
import { Route as AuthenticatedAgentLinksRouteImport } from './routes/_authenticated/agent.links'
import { Route as AuthenticatedAgentOrdersRouteImport } from './routes/_authenticated/agent.orders'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as BuyTokenIndexRouteImport } from './routes/buy.$token.index'
import { Route as BuyTokenCheckoutRouteImport } from './routes/buy.$token.checkout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BuyTokenRoute = BuyTokenRouteImport.update({
  id: '/buy/$token',
  path: '/buy/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceOrderNumberRoute = InvoiceOrderNumberRouteImport.update({
  id: '/invoice/$orderNumber',
  path: '/invoice/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderNumberRoute = OrderOrderNumberRouteImport.update({
  id: '/order/$orderNumber',
  path: '/order/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAgentsRoute =
  AuthenticatedAdminAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSalesRoute = AuthenticatedAdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAgentIndexRoute = AuthenticatedAgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAgentRoute,
} as any)
const AuthenticatedAgentCustomersRoute =
  AuthenticatedAgentCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentLinksRoute = AuthenticatedAgentLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedAgentRoute,
} as any)
const AuthenticatedAgentOrdersRoute =
  AuthenticatedAgentOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const BuyTokenIndexRoute = BuyTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuyTokenRoute,
} as any)
const BuyTokenCheckoutRoute = BuyTokenCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => BuyTokenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agent': typeof AuthenticatedAgentRouteWithChildren
  '/buy/$token': typeof BuyTokenRouteWithChildren
  '/invoice/$orderNumber': typeof InvoiceOrderNumberRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/agent/customers': typeof AuthenticatedAgentCustomersRoute
  '/agent/links': typeof AuthenticatedAgentLinksRoute
  '/agent/orders': typeof AuthenticatedAgentOrdersRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/buy/$token/checkout': typeof BuyTokenCheckoutRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/agent/': typeof AuthenticatedAgentIndexRoute
  '/buy/$token/': typeof BuyTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invoice/$orderNumber': typeof InvoiceOrderNumberRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/agent/customers': typeof AuthenticatedAgentCustomersRoute
  '/agent/links': typeof AuthenticatedAgentLinksRoute
  '/agent/orders': typeof AuthenticatedAgentOrdersRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/buy/$token/checkout': typeof BuyTokenCheckoutRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/agent': typeof AuthenticatedAgentIndexRoute
  '/buy/$token': typeof BuyTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agent': typeof AuthenticatedAgentRouteWithChildren
  '/buy/$token': typeof BuyTokenRouteWithChildren
  '/invoice/$orderNumber': typeof InvoiceOrderNumberRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/_authenticated/agent/customers': typeof AuthenticatedAgentCustomersRoute
  '/_authenticated/agent/links': typeof AuthenticatedAgentLinksRoute
  '/_authenticated/agent/orders': typeof AuthenticatedAgentOrdersRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/buy/$token/checkout': typeof BuyTokenCheckoutRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/agent/': typeof AuthenticatedAgentIndexRoute
  '/buy/$token/': typeof BuyTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/agent'
    | '/buy/$token'
    | '/invoice/$orderNumber'
    | '/order/$orderNumber'
    | '/product/$slug'
    | '/admin/admins'
    | '/admin/agents'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/sales'
    | '/agent/customers'
    | '/agent/links'
    | '/agent/orders'
    | '/api/public/razorpay-webhook'
    | '/buy/$token/checkout'
    | '/admin/'
    | '/agent/'
    | '/buy/$token/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/invoice/$orderNumber'
    | '/order/$orderNumber'
    | '/product/$slug'
    | '/admin/admins'
    | '/admin/agents'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/sales'
    | '/agent/customers'
    | '/agent/links'
    | '/agent/orders'
    | '/api/public/razorpay-webhook'
    | '/buy/$token/checkout'
    | '/admin'
    | '/agent'
    | '/buy/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/agent'
    | '/buy/$token'
    | '/invoice/$orderNumber'
    | '/order/$orderNumber'
    | '/product/$slug'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/agents'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/sales'
    | '/_authenticated/agent/customers'
    | '/_authenticated/agent/links'
    | '/_authenticated/agent/orders'
    | '/api/public/razorpay-webhook'
    | '/buy/$token/checkout'
    | '/_authenticated/admin/'
    | '/_authenticated/agent/'
    | '/buy/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuyTokenRoute: typeof BuyTokenRouteWithChildren
  InvoiceOrderNumberRoute: typeof InvoiceOrderNumberRoute
  OrderOrderNumberRoute: typeof OrderOrderNumberRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/buy/$token': {
      id: '/buy/$token'
      path: '/buy/$token'
      fullPath: '/buy/$token'
      preLoaderRoute: typeof BuyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$orderNumber': {
      id: '/invoice/$orderNumber'
      path: '/invoice/$orderNumber'
      fullPath: '/invoice/$orderNumber'
      preLoaderRoute: typeof InvoiceOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderNumber': {
      id: '/order/$orderNumber'
      path: '/order/$orderNumber'
      fullPath: '/order/$orderNumber'
      preLoaderRoute: typeof OrderOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/agents': {
      id: '/_authenticated/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AuthenticatedAdminAgentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sales': {
      id: '/_authenticated/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AuthenticatedAdminSalesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/agent/': {
      id: '/_authenticated/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AuthenticatedAgentIndexRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/agent/customers': {
      id: '/_authenticated/agent/customers'
      path: '/customers'
      fullPath: '/agent/customers'
      preLoaderRoute: typeof AuthenticatedAgentCustomersRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/agent/links': {
      id: '/_authenticated/agent/links'
      path: '/links'
      fullPath: '/agent/links'
      preLoaderRoute: typeof AuthenticatedAgentLinksRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/agent/orders': {
      id: '/_authenticated/agent/orders'
      path: '/orders'
      fullPath: '/agent/orders'
      preLoaderRoute: typeof AuthenticatedAgentOrdersRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$token/': {
      id: '/buy/$token/'
      path: '/'
      fullPath: '/buy/$token/'
      preLoaderRoute: typeof BuyTokenIndexRouteImport
      parentRoute: typeof BuyTokenRoute
    }
    '/buy/$token/checkout': {
      id: '/buy/$token/checkout'
      path: '/checkout'
      fullPath: '/buy/$token/checkout'
      preLoaderRoute: typeof BuyTokenCheckoutRouteImport
      parentRoute: typeof BuyTokenRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminAgentsRoute: typeof AuthenticatedAdminAgentsRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminSalesRoute: typeof AuthenticatedAdminSalesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
  AuthenticatedAdminAgentsRoute: AuthenticatedAdminAgentsRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminSalesRoute: AuthenticatedAdminSalesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAgentRouteChildren {
  AuthenticatedAgentCustomersRoute: typeof AuthenticatedAgentCustomersRoute
  AuthenticatedAgentLinksRoute: typeof AuthenticatedAgentLinksRoute
  AuthenticatedAgentOrdersRoute: typeof AuthenticatedAgentOrdersRoute
  AuthenticatedAgentIndexRoute: typeof AuthenticatedAgentIndexRoute
}

const AuthenticatedAgentRouteChildren: AuthenticatedAgentRouteChildren = {
  AuthenticatedAgentCustomersRoute: AuthenticatedAgentCustomersRoute,
  AuthenticatedAgentLinksRoute: AuthenticatedAgentLinksRoute,
  AuthenticatedAgentOrdersRoute: AuthenticatedAgentOrdersRoute,
  AuthenticatedAgentIndexRoute: AuthenticatedAgentIndexRoute,
}

const AuthenticatedAgentRouteWithChildren =
  AuthenticatedAgentRoute._addFileChildren(AuthenticatedAgentRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgentRoute: AuthenticatedAgentRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BuyTokenRouteChildren {
  BuyTokenCheckoutRoute: typeof BuyTokenCheckoutRoute
  BuyTokenIndexRoute: typeof BuyTokenIndexRoute
}

const BuyTokenRouteChildren: BuyTokenRouteChildren = {
  BuyTokenCheckoutRoute: BuyTokenCheckoutRoute,
  BuyTokenIndexRoute: BuyTokenIndexRoute,
}

const BuyTokenRouteWithChildren = BuyTokenRoute._addFileChildren(
  BuyTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuyTokenRoute: BuyTokenRouteWithChildren,
  InvoiceOrderNumberRoute: InvoiceOrderNumberRoute,
  OrderOrderNumberRoute: OrderOrderNumberRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
